opentelemetry-collector:
  image:
    repository: "otel/opentelemetry-collector-contrib"
    pullPolicy: IfNotPresent
    tag: ""
    digest: ""
  imagePullSecrets: []

  mode: "deployment"
  
  configMap:
    create: true
    existingName: ""

  config:
    exporters:
      otlp/tempo:
        endpoint: grafana-tempo-distributor.observability.svc.cluster.local:4317
        tls:
          insecure: true
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
    service:
      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: ${env:MY_POD_IP}
                    port: 8888
      extensions:
        - health_check
      pipelines:
        traces:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch
          exporters:
            - otlp/tempo

  serviceAccount:
    create: true
    annotations: {}
    name: ""
    automountServiceAccountToken: true

  nodeSelector: 
    eks.amazonaws.com/nodegroup: "dev-app-system"
  tolerations: 
    - key: "node-group"
      operator: "Equal"
      value: "observability"
      effect: "NoSchedule"

  priorityClassName: "system-cluster-critical"

  ports:
    otlp:
      enabled: true
      containerPort: 4317
      servicePort: 4317
      hostPort: 4317
      protocol: TCP
      appProtocol: grpc
    otlp-http:
      enabled: true
      containerPort: 4318
      servicePort: 4318
      hostPort: 4318
      protocol: TCP
    jaeger-compact:
      enabled: false
    jaeger-thrift:
      enabled: false
    jaeger-grpc:
      enabled: false
    zipkin:
      enabled: false
    metrics:
      enabled: false
