{{ range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-namespace
  namespace: {{ $.Values.argocdNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: {{ .path }}
    repoURL: {{ .repoURL }}
    targetRevision: HEAD
    helm:
      releaseName: {{ .name }}
      valueFiles:
        - values-{{ $.Values.env }}.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{ end }}