loki:
  loki:
    auth_enabled: false
    schemaConfig:
      configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    storage_config:
      aws:
        region: ap-northeast-1
        bucketnames: aws-log-loki
        s3forcepathstyle: false
    pattern_ingester:
        enabled: true
    limits_config:
      allow_structured_metadata: true
      volume_enabled: true
      retention_period: 672h # 28 days retention
    querier:
      max_concurrent: 4

    storage:
      type: s3
      bucketNames:
          chunks: aws-log-loki
          ruler: aws-log-rule
          admin: aws-log-admin
      s3:
        region: ap-northeast-1
        s3ForcePathStyle: false
        insecure: false
        http_config: {}

  deploymentMode: SimpleScalable

  serviceAccount:
    create: true
    annotations:
      "eks.amazonaws.com/role-arn": "arn:aws:iam::412723383795:role/sandbox-app-loki-eks-irsa-role" 

  backend:
    replicas: 3
    autoscaling:
      enabled: false
    tolerations:
    - key: "node-group"
      operator: "Equal"
      value: "system"
      effect: "NoExecute"
  read:
    replicas: 3
    autoscaling:
      enabled: false
    tolerations:
    - key: "node-group"
      operator: "Equal"
      value: "system"
      effect: "NoExecute"
  write:
    replicas: 3
    autoscaling:
      enabled: false
    tolerations:
    - key: "node-group"
      operator: "Equal"
      value: "system"
      effect: "NoExecute"
  chunksCache:
    replicas: 1
    allocatedMemory: 1024
    autoscaling:
      enabled: false
    tolerations:
    - key: "node-group"
      operator: "Equal"
      value: "system"
      effect: "NoExecute"

  test:
    enabled: false

  lokiCanary:
    enabled: false

  # Disable minio storage
  minio:
    enabled: false