apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: {{ $.Values.argocdNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: aws-load-balancer-controller
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/system/aws-load-balancer-controller/{{ $.Values.env }}
    repoURL: https://github.com/platform-argo-cd.git
    targetRevision: HEAD
    helm:
      releaseName: aws-load-balancer-controller
      valueFiles:
        - values-{{ $.Values.env }}.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true