apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: {{ $.Values.argocdNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/cert-manager/{{ $.Values.env }}
    repoURL: https://github.com/application-org/platform-argo-cd.git
    targetRevision: HEAD
    helm:
      releaseName: cert-manager
      valueFiles:
        - values-{{ $.Values.env }}.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true