apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-public
  namespace: {{ $.Values.argocdNamespace }}
  finalizers: 
    - resources-finalizer.argocd.argoproj.io
spec: 
  destination:
    namespace: external-dns-public
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/system/external-dns-public/{{ $.Values.env }}
    repoURL: https://github.com/platform-argo-cd.git
    targetRevision: HEAD
    helm:
      releaseName: external-dns-public
      valueFiles:
        - values-{{ $.Values.env }}.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true