loki:
  deploymentMode: SimpleScalable
  
  serviceAccount:
    create: true
    annotations:
      "eks.amazonaws.com/role-arn": "arn:aws:iam::xxx:role/dev-app-grafana-loki-eks-irsa-role" 

  loki:
    storage:
      type: s3
      bucketNames:
        chunks: application-log-loki
        ruler: application-log-loki
        admin: application-log-loki
      s3:
        region: ap-northeast-1

    server:
      grpc_server_max_recv_msg_size: 104857600 # 100MB
      grpc_server_max_send_msg_size: 104857600 # 100MB

    commonConfig:
      replication_factor: 1

    storage_config:
      disable_broad_index_queries: true

    ingester:
      chunk_encoding: snappy
      wal:
        flush_on_shutdown: true

    limits_config:
      # write
      max_global_streams_per_user: 20000
      ingestion_rate_mb: 20
      ingestion_burst_size_mb: 30
      per_stream_rate_limit: 10MB
      per_stream_rate_limit_burst: 15MB
      cardinality_limit: 500000
      # read
      split_queries_by_interval: 15m
      max_query_parallelism: 128
      max_query_series: 1000
      # misc
      enforce_metric_name: false

    querier:
      max_concurrent: 16

    query_scheduler:
      max_outstanding_requests_per_tenant: 2048

    frontend:
      compress_responses: true
      log_queries_longer_than: 20s

    compactor:
      retention_enabled: true
      delete_request_cancel_period: 1h


  gateway:
    replicas: 2
    basicAuth:
      enabled: true
    autoscaling:
      enabled: true

  backend:
    replicas: 3
    autoscaling:
      enabled: false
    tolerations:
    - key: "node-group"
      operator: "Equal"
      value: "system"
      effect: "NoExecute"
    nodeSelector:
      eks.amazonaws.com/nodegroup: dev-app-observability

  read:
    replicas: 3
    legacyReadTarget: true
    extraArgs:
      - -log-config-reverse-order
    autoscaling:
      enabled: false
    persistence:
      size: "50Gi"

    nodeSelector:
      eks.amazonaws.com/nodegroup: dev-app-observability

    tolerations:
    - key: "node-group"
      operator: "Equal"
      value: "observability"
      effect: "NoSchedule"

  write:
    replicas: 3
    extraArgs:
      - -log-config-reverse-order
    autoscaling:
      enabled: false
    persistence:
      size: "50Gi"

    nodeSelector:
      eks.amazonaws.com/nodegroup: dev-app-observability

    tolerations:
    - key: "node-group"
      operator: "Equal"
      value: "observability"
      effect: "NoSchedule"

  monitoring:
    rules:
      enabled: false
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
    lokiCanary:
      enabled: false
  test:
    enabled: false

  lokiCanary:
    enabled: false

  minio:
    enabled: false