apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki
  namespace: {{ $.Values.argocdNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: grafana-loki
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/observability/grafana-loki/{{ $.Values.env }}
    repoURL: https://github.com/platform-argo-cd.git
    targetRevision: HEAD
    helm:
      releaseName: grafana-loki
      valueFiles:
        - values-{{ $.Values.env }}.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true