apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: {{ $.Values.argocdNamespace }}
  finalizers: 
    - resources-finalizer.argocd.argoproj.io
spec: 
  destination:
    namespace: opentelemetry-collector
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/observability/opentelemetry-collector/{{ $.Values.env }}
    repoURL: https://github.com/platform-argo-cd.git
    targetRevision: HEAD
    helm:
      releaseName: opentelemetry-collector
      valueFiles:
        - values-{{ $.Values.env }}.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true